# Generated by Django 4.2.4 on 2023-09-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='peoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_img', models.ImageField(upload_to='photo')),
                ('p_desc', models.TextField()),
            ],
        ),
    ]
