# Generated by Django 4.2.4 on 2023-09-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_peoples'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoples',
            old_name='p_desc',
            new_name='pdesc',
        ),
        migrations.RenameField(
            model_name='peoples',
            old_name='p_img',
            new_name='pimg',
        ),
        migrations.RenameField(
            model_name='peoples',
            old_name='p_name',
            new_name='pname',
        ),
    ]
